# Generated by Django 4.2.7 on 2023-12-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pick_posts',
            field=models.BooleanField(default=False),
        ),
    ]
